name: Build & Deploy Laravel to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # -----------------------------
      # SETUP PHP
      # -----------------------------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo, pdo_mysql, openssl, intl, tokenizer

      # -----------------------------
      # COMPOSER INSTALL
      # -----------------------------
      - name: Composer install
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction

      # -----------------------------
      # NODE, NPM, VITE BUILD
      # -----------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM packages + Terser + Build Vite
        run: |
          npm install
          npm install terser
          npm run build

      # ----------------------------------
      # MOVE LARAVEL PUBLIC CONTENT TO ROOT (WAJIB DI AZURE)
      # ----------------------------------
      - name: Move public/ to root
        run: |
          cp -r public/* .
          rm -rf public

      # ----------------------------------
      # REMOVE DEFAULT AZURE PAGE
      # ----------------------------------
      - name: Remove hostingstart.html
        run: rm -f hostingstart.html

      # ----------------------------------
      # UPLOAD ARTIFACT
      # ----------------------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      # -----------------------------
      # LOGIN KE AZURE (PAKAI SECRET BAWAAN)
      # -----------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B0DB85468AE4789B24A686120AC2AF2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A8AA1E6BE0744D669A1D326658F9466E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B2AAC9E2530413B8B4E39F5205D58EC }}

      # -----------------------------
      # DEPLOY KE AZURE
      # -----------------------------
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "kpborju"
          slot-name: "Production"
          package: .
