name: Build & Deploy Laravel to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # SETUP PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql, openssl, intl, tokenizer

      # COMPOSER INSTALL
      - name: Composer install
        run: composer install --no-dev --optimize-autoloader

      # NODE / VITE
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies & build assets
        run: |
          npm install
          npm install terser
          npm run build

      # COPY FILE YANG DIBUTUHKAN KE FOLDER DEPLOY
      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -R public/* deploy/
          cp -R vendor deploy/vendor
          cp -R storage deploy/storage
          cp server.php deploy/index.php

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kpborju'
          package: .
