name: Build and Deploy Laravel to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      # Checkout source
      - uses: actions/checkout@v4

      # ---------- PHP SETUP ----------
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: none

      # ---------- COMPOSER ----------
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # ---------- NODE SETUP ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ---------- NPM ----------
      - name: Install NPM dependencies
        run: npm install terser

      - name: Build assets
        run: npm run build

      # ---------- CREATE HTACCESS ----------
      - name: Fix Rewrite Rules for Azure
        run: |
          cat << 'EOF' > public/.htaccess
          <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteRule ^ index.php [L]
          </IfModule>
          EOF

      # ---------- PREPARE DEPLOY PACKAGE ----------
      - name: Create deployment folder
        run: |
          mkdir deploy
          rsync -av \
            --exclude="node_modules" \
            --exclude="vendor" \
            --exclude=".git" \
            --exclude="tests" \
            . ./deploy

      # ---------- UPLOAD ARTIFACT ----------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-package
          path: deploy


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-package

      # Azure Deployment
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "kedaisambelborju"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
