name: Build and deploy Laravel to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: none

      # Composer Install
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # NPM Install + Build
      - name: Install NPM dependencies
        run: npm install terser 
              npm install

      - name: Build Frontend (Vite)
        run: npm run build
        # Jika pakai Laravel Mix ganti:
        # run: npm run prod

      # Copy Laravel public files to root
      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -R . deploy
          rm -rf deploy/node_modules
          rm -rf deploy/tests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "kedaisambelborju"
          slot-name: "Production"
          publish-profile: ${{ secrets.__publishingprofilesecretname__ }}
          package: .
